tag-prefix = "v"
pre-release-commit-message = "Release {{version}} 🎉🎉"

[[pre-release-replacements]]
file="CHANGELOG.md"
search="## \\[Unreleased\\] — ReleaseDate"
replace="## [Unreleased] — ReleaseDate\n\n## [{{version}}] — {{date}}"
